-- 회원 시퀀스
DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ;

-- 물품 시퀀스
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;

-- 판매 시퀀스
DROP SEQUENCE SELL_SEQ;
CREATE SEQUENCE SELL_SEQ;

-- 장바구니 시퀀스
DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ;

-- 공지사항 시퀀스
DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ;

-- 자유게시판 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ;

-- 커뮤니티게시판 시퀀스
DROP SEQUENCE COMMUNITY_SEQ;
CREATE SEQUENCE COMMUNITY_SEQ;

-- 상담신청 시퀀스
DROP SEQUENCE VISIT_SEQ;
CREATE SEQUENCE VISIT_SEQ;

DROP TABLE TB_COM_CODE CASCADE CONSTRAINT;
CREATE TABLE TB_COM_CODE(
  COMM_TY_CD VARCHAR2(10),
  COMM_CD VARCHAR2(20),
  COMM_CD_NM VARCHAR2(30),
  CONSTRAINT TB_CODE_PK PRIMARY KEY(COMM_TY_CD, COMM_CD)
);

-- 전화번호
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '01', '010');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '02', '011');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '03', '016');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '04', '019');

-- PROODUCT 카케고리 분류코드
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'P', 'perfume');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'D', 'diffuser');

--회원정보
DROP TABLE TB_COM_USER CASCADE CONSTRAINT;
CREATE TABLE TB_COM_USER(
  USER_CODE VARCHAR2(20),             -- 유저코드
  ID VARCHAR2(20),                    -- 아이디
  PW VARCHAR2(20),                    -- 패스워드
  EMAIL VARCHAR2(50),                 -- 이메일
  NAME VARCHAR2(20),                  -- 이름
  BIRTH VARCHAR2(20),                 -- 생일
  POST_NUM VARCHAR2(20),              -- 우편번호
  PHONE_CD VARCHAR2(2),               -- 전화번호앞자리 코드
  PHONE_NUM VARCHAR2(20),             -- 전화번호뒷자리
  ADDRESS VARCHAR2(100),              -- 주소
  ENT_DATE VARCHAR2(30),              -- 회원가입일
  GRADE VARCHAR2(1) DEFAULT 'M',	  -- 회원등급
  CONSTRAINT TB_COM_USER_PK PRIMARY KEY(USER_CODE)
);

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'admin', 'admin', 'admin@aroma_fragansia.com', 'AROMA', '1980-02-12', '06232',
          '01', '1234-5678', '서울특별시 강남구 강남대로 382', '2022-10-13', 'A');
INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'ksy', 'ksy', 'ksy@naver.com', '기성용', '1989-01-12', '06021',
          '01', '1111-2222', '서울특별시 강남구 신사동 651-7', '2023-01-18');
INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'shm', 'shm', 'shm@naver.com', '손흥민', '1992-05-07', '06021',
          '01', '3333-4444', '서울특별시 강남구 도산대로45길 7', '2023-01-18');

commit;

--제품정보
DROP TABLE TB_PRODUCT CASCADE CONSTRAINT;
CREATE TABLE TB_PRODUCT(
  PRODUCT_CODE VARCHAR2(20),                  -- 제품코드
  PRODUCT_IMAGE VARCHAR2(70),                 -- 제품이미지
  PRODUCT_NAME VARCHAR2(200),                 -- 제품명
  PRODUCT_UNIT_PRICE NUMBER,		    	  -- 제품단가
  PRODUCT_COUNT NUMBER,						  -- 제품재고수량
  PRODUCT_CATEGORY_CD VARCHAR2(20),           -- 제품코드
  PRODUCT_REG_DATE VARCHAR2(20),              -- 제품등록일
  CONSTRAINT TB_PRODUCT_PK PRIMARY KEY(PRODUCT_CODE)
);

-- perfume 제품 등록
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p1.png', 'Fragancia 642', 75000, 2, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p2.png', 'Fragancia 772', 75000, 10, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p3.png', 'Fragancia 201', 75000, 30, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p4.png', 'Fragancia Mini-Gift-Set', 150000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p5.png', 'Fragancia Signature', 140000, 35, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p6.png', 'Miss Fragancia', 73000, 15, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p7.png', 'Fragancia 944', 75000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p8.png', 'Fragancia Cassis', 80000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p9.png', 'Fragancia UOMO', 120000, 50, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p10.png', 'Fragancia 342', 75000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p11.png', 'Fragancia 641', 75000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('P00' || PRODUCT_SEQ.NEXTVAL, 'p12.png', 'Fragancia 207', 10000, 20, 'P', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

-- diffuser 제품 등록
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd1.png', 'Fragancia 642', 75000, 10, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd2.png', 'Fragancia 772', 75000, 15, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd3.png', 'Fragancia 201', 75000, 20, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd4.png', 'Fragancia Mini-Gift-Set', 150000, 4, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd5.png', 'Fragancia Signature', 140000, 78, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd6.png', 'Miss Fragancia', 73000, 25, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd7.png', 'Fragancia 944', 75000, 23, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd8.png', 'Fragancia Cassis', 80000, 100, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd9.png', 'Fragancia UOMO', 120000, 25, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd10.png', 'Fragancia 342', 75000, 34, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd11.png', 'Fragancia 641', 75000, 6, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_NAME, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('D00' || PRODUCT_SEQ.NEXTVAL, 'd12.png', 'Fragancia 207', 10000, 19, 'D', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

--판매내역정보
DROP TABLE TB_SELL CASCADE CONSTRAINT;
CREATE TABLE TB_SELL(
  SELL_CODE VARCHAR2(20),          -- 판매내역코드
  PRODUCT_CODE VARCHAR2(20),       -- 제품코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  SELL_PRICE NUMBER,      		   -- 판매총가격
  SELL_COUNT NUMBER,     		   -- 판매총수량
  SELL_YN VARCHAR2(1) DEFAULT 'N', -- 판매여부
  SELL_DATE VARCHAR2(30),          -- 판매일
  CONSTRAINT TB_SELL_PK PRIMARY KEY(SELL_CODE),
  CONSTRAINT TB_SELL_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_SELL_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--장바구니정보
DROP TABLE TB_CART CASCADE CONSTRAINT;
CREATE TABLE TB_CART(
  CART_CODE VARCHAR2(20),          -- 장바구니코드
  PRODUCT_CODE VARCHAR2(20),       -- 제품코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  CART_PRICE NUMBER,   		       -- 해당제품총가격
  CART_COUNT NUMBER,   		       -- 해당제품총수량
  CART_DATE VARCHAR2(30),          -- 장바구니 저장일
  CONSTRAINT TB_CART_PK PRIMARY KEY(CART_CODE),
  CONSTRAINT TB_CART_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_CART_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--댓글정보
DROP TABLE TB_REPLY CASCADE CONSTRAINT;
CREATE TABLE TB_REPLY(
  PRODUCT_CODE VARCHAR2(30),       -- 투표코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  USER_REPLY_NO NUMBER(3),         -- 댓글일련번호
  USER_REPLY VARCHAR2(1000),       -- 댓글내용
  REPLY_DATE VARCHAR2(30),         -- 댓글날짜
  CONSTRAINT TB_REPLY_PK PRIMARY KEY(PRODUCT_CODE, USER_CODE, USER_REPLY_NO),
  CONSTRAINT TB_REPLY_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_REPLY_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--별점정보
DROP TABLE TB_MARK CASCADE CONSTRAINT;
CREATE TABLE TB_MARK(
  PRODUCT_CODE VARCHAR2(30),       -- 투표코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  MARK_RATING NUMBER,        	   -- 별점(5점만점)
  CONSTRAINT TB_MARK_PK PRIMARY KEY(PRODUCT_CODE, USER_CODE),
  CONSTRAINT TB_MARK_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_MARK_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

commit;

-- 공지사항 정보
-- 제약조건이 있는 테이블일 경우 DROP시 CASECADE CONSTRAINTS 옵션을 사용
DROP TABLE TB_NOTICE CASCADE CONSTRAINT;
CREATE TABLE TB_NOTICE(
  NTC_NO VARCHAR2(20),   	      	  -- 글번호
  NTC_TITLE VARCHAR2(50) NOT NULL,    -- 제목
  NTC_CONTENT VARCHAR2(4000), 	 	  -- 내용
  NTC_REG_ID VARCHAR2(20),    	 	  -- 등록자(수정자와 동일)
  NTC_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  NTC_MOD_DATE VARCHAR2(20),   		  -- 수정일자
  NTC_HIT NUMBER DEFAULT 0,    		  -- 조회수
  CONSTRAINT TB_NOTICE_PK PRIMARY KEY(NTC_NO)
);

-- 자유게시판 정보
DROP TABLE TB_BOARD CASCADE CONSTRAINT;
CREATE TABLE TB_BOARD(
  BO_NO VARCHAR2(20),           	  -- 글번호
  BO_TITLE VARCHAR2(50) NOT NULL, 	  -- 제목
  BO_CONTENT VARCHAR2(4000),   	  	  -- 내용
  BO_REG_ID VARCHAR2(20),      	  	  -- 등록자
  BO_MOD_ID VARCHAR2(20),       	  -- 수정자
  BO_REG_DATE VARCHAR2(20),     	  -- 등록일자
  BO_MOD_DATE VARCHAR2(20),     	  -- 수정일자
  BO_HIT NUMBER DEFAULT 0,     	  	  -- 조회수
  CONSTRAINT TB_BOARD_PK PRIMARY KEY(BO_NO)
);

-- 커뮤니티게시판 정보
DROP TABLE TB_COMMUNITY CASCADE CONSTRAINT;
CREATE TABLE TB_COMMUNITY(
  COMU_NO VARCHAR2(20),            	  -- 글번호
  COMU_TITLE VARCHAR2(50) NOT NULL,   -- 제목
  COMU_CONTENT VARCHAR2(4000),    	  -- 내용
  COMU_REG_ID VARCHAR2(20),      	  -- 등록자
  COMU_MOD_ID VARCHAR2(20),       	  -- 수정자
  COMU_REG_DATE VARCHAR2(20),     	  -- 등록일자
  COMU_MOD_DATE VARCHAR2(20),     	  -- 수정일자
  COMU_HIT NUMBER DEFAULT 0,      	  -- 조회수
  CONSTRAINT TB_COMMUNITY_PK PRIMARY KEY(COMU_NO)
);

-- 상담신청 정보
DROP TABLE TB_VISIT CASCADE CONSTRAINT;
CREATE TABLE TB_VISIT(
  VST_NO VARCHAR2(20),            	  -- 글번호
  VST_TITLE VARCHAR2(50) NOT NULL,    -- 제목
  VST_CONTENT VARCHAR2(4000),  		  -- 내용
  VST_PHONE VARCHAR2(30),         	  -- 전화번호
  VST_EMAIL VARCHAR2(50),     	      -- 이메일
  VST_REG_ID VARCHAR2(20),   	      -- 등록자
  VST_MOD_ID VARCHAR2(20),   	      -- 수정자
  VST_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  VST_MOD_DATE VARCHAR2(20),  	   	  -- 수정일자
  CONSTRAINT TB_VISIT_PK PRIMARY KEY(VST_NO)
);

commit;