-- eye 제품 등록
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE) 
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e1.png', 'e1_over.png', '라이스페이퍼', 'EYE SHADOW', '화려한 펄감과 함께 광택감나는 피치 골드', 33000, 0, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e2.png', 'e2_over.png', '카본', 'EYE SHADOW', '가장 부드럽고 풍부한 블랙', 33000, 10, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e3.png', 'e3_over.png', '다크룸', 'EYE SHADOW', '차가운 퍼플', 33000, 30, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e4.png', 'e4_over.png', '그레이스톤', 'EYE SHADOW', '차가운 중간 톤의 그레이', 33000, 20, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e5.png', 'e5_over.png', '다즐라이트', 'EYE SHADOW', '실버 펄이 함유된 깨끗한 화이트', 33000, 35, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e6.png', 'e6_over.png', '코르크', 'EYE SHADOW', '소프트한 골든 브라운', 33000, 15, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e7.png', 'e7_over.png', '아임 인투 잇', 'EYE SHADOW', '다크 레드 브라운', 33000, 20, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('E00' || PRODUCT_SEQ.NEXTVAL, 'e8.png', 'e8_over.png', '앰버 라이트', 'EYE SHADOW', '골드 펄감의 라이트 브라운', 33000, 20, 'E', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

-- face 제품 등록
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f1.png', 'f1_over.png', '라이트풀 C3 파운데이션', 'LIGHTFUL C3 FOUNDATION', '리퀴드 파운데이션', 33000, 0, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f2.png', 'f2_over.png', '롱웨어 너리싱 파운데이션', 'LONGWEAR FOUNDATION', '롱웨어 프루프 포뮬라', 67000, 15, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f3.png', 'f3_over.png', '프로 너리싱 파운데이션', 'PRO NOURISHING FOUNDATION', '프로 프루프 포뮬라', 67000, 20, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f4.png', 'f4_over.png', '밸런싱 플루이드 파운데이션', 'BALANCING FLUID FOUNDATION', '모이스처-퓨전 콤플렉스 성분으로 가벼운 텍스처', 67000, 4, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f5.png', 'f5_over.png', '로즈 톤업 멀티밤', 'LIGHTFUL C3 TONE-UP BALM', 'NO.1 베이스 로즈 톤업 베이스의 밤 버전', 63000, 78, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f6.png', 'f6_over.png', '픽스 플루이드 파운데이션', 'FIX FLUID FOUNDATION', '내추럴 매트 텍스처 롱웨어링 파운데이션', 62000, 25, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f7.png', 'f7_over.png', '퀵 피니쉬 쿠션', 'QUICK FINISH CUSHION', '얇지만 완벽한 커버력으로 롱웨어링 커버', 55000, 23, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('F00' || PRODUCT_SEQ.NEXTVAL, 'f8.png', 'f8_over.png', '픽스 플루이드 파운데이션', 'FIX FLUID FOUNDATION', '내추럴 매트 텍스처 롱웨어링 파운데이션', 62000, 100, 'F', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

-- lip 제품 등록
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l1.png', 'l1_over.png', '비바 글램 I', 'VIVA GLAM LIPSTICK', '강렬한 브라운 빛의 블루 레드', 33000, 0, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l2.png', 'l2_over.png', '비바 글램 II', 'VIVA GLAM LIPSTICK', '펄감이 있는 연한 핑크 베이지', 33000, 15, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l3.png', 'l3_over.png', '비바 글램 III', 'VIVA GLAM LIPSTICK', '연한 브라운 빛 플럼', 33000, 20, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l4.png', 'l4_over.png', '러시안 레드', 'MATTE LIPSTICK', '강렬한 블루빛 레드', 34000, 4, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l5.png', 'l5_over.png', '글로우 플레이 립 밤', 'GLOW PLAY LIP BALM', '브라이트 레드', 34000, 78, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l6.png', 'l6_over.png', '로즈 투 디 오케이젼', 'GLOW PLAY LIP BALM', '로지 핑크', 34000, 25, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l7.png', 'l7_over.png', '댓 티클스', 'GLOW PLAY LIP BALM', '딥 누드', 34000, 23, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_PRODUCT(PRODUCT_CODE, PRODUCT_IMAGE, PRODUCT_IMAGE2, PRODUCT_NAME, PRODUCT_NAME_ENG, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE, PRODUCT_COUNT,  PRODUCT_CATEGORY_CD, PRODUCT_REG_DATE)
VALUES('L00' || PRODUCT_SEQ.NEXTVAL, 'l8.png', 'l8_over.png', '플로랄 코랄', 'GLOW PLAY LIP BALM', '베리 핑크', 34000, 100, 'L', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

commit;
