-- 회원 시퀀스
DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ;

-- 제품 시퀀스
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;

-- 판매 시퀀스
DROP SEQUENCE SELL_SEQ;
CREATE SEQUENCE SELL_SEQ;

-- 장바구니 시퀀스
DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ;

-- 공지사항 시퀀스
DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ;

-- 이벤트시퀀스
DROP SEQUENCE EVENT_SEQ;
CREATE SEQUENCE EVENT_SEQ;

-- 커뮤니티게시판 시퀀스
DROP SEQUENCE COMMUNITY_SEQ;
CREATE SEQUENCE COMMUNITY_SEQ;

-- 1:1문의 시퀀스
DROP SEQUENCE INQUIRY_SEQ;
CREATE SEQUENCE INQUIRY_SEQ;

-- 갤러리 시퀀스
DROP SEQUENCE GALERY_SEQ;
CREATE SEQUENCE GALERY_SEQ;

-- QNA 시퀀스
DROP SEQUENCE QNA_SEQ;
CREATE SEQUENCE QNA_SEQ;

-- QNA 댓글 시퀀스
DROP SEQUENCE QNA_REPLY_SEQ;
CREATE SEQUENCE QNA_REPLY_SEQ;

DROP TABLE TB_COM_CODE CASCADE CONSTRAINT;
CREATE TABLE TB_COM_CODE(
  COMM_TY_CD VARCHAR2(10),
  COMM_CD VARCHAR2(20),
  COMM_CD_NM VARCHAR2(30),
  CONSTRAINT TB_CODE_PK PRIMARY KEY(COMM_TY_CD, COMM_CD)
);

-- 전화번호
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '01', '010');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '02', '011');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '03', '016');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '04', '019');

-- PROODUCT 카케고리 분류코드
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'E', '섀도우');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'F', '파운데이션');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'L', '립');

--회원정보
DROP TABLE TB_COM_USER CASCADE CONSTRAINT;
CREATE TABLE TB_COM_USER(
  USER_CODE VARCHAR2(20),             -- 유저코드
  ID VARCHAR2(20),                    -- 아이디
  PW VARCHAR2(20),                    -- 패스워드
  EMAIL VARCHAR2(50),                 -- 이메일
  NAME VARCHAR2(20),                  -- 이름
  BIRTH VARCHAR2(20),                 -- 생일
  POST_NUM VARCHAR2(20),              -- 우편번호
  PHONE_CD VARCHAR2(2),               -- 전화번호앞자리 코드
  PHONE_NUM VARCHAR2(20),             -- 전화번호뒷자리
  ADDRESS VARCHAR2(100),              -- 주소
  ENT_DATE VARCHAR2(30),              -- 회원가입일
  GRADE VARCHAR2(1) DEFAULT 'M',	  -- 회원등급
  CONSTRAINT TB_COM_USER_PK PRIMARY KEY(USER_CODE)
);

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'glowup', 'glowup', 'glowup@glow_up.com', 'GLOWUP', '1980-02-12', '06232',
          '01', '1234-5678', '서울특별시 강남구 강남대로 382', '2023-03-02', 'A');
INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'ksy', 'ksy', 'ksy@naver.com', '기성용', '1989-01-12', '06021',
          '01', '1111-2222', '서울특별시 강남구 신사동 651-7', '2023-03-29');
INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'shm', 'shm', 'shm@naver.com', '손흥민', '1992-05-07', '06021',
          '01', '3333-4444', '서울특별시 강남구 도산대로45길 7', '2023-03-29');

commit;

--제품정보
DROP TABLE TB_PRODUCT CASCADE CONSTRAINT;
CREATE TABLE TB_PRODUCT(
  PRODUCT_CODE VARCHAR2(20),                  -- 제품코드
  PRODUCT_IMAGE VARCHAR2(70),                 -- 제품이미지1
  PRODUCT_IMAGE2 VARCHAR2(70),                -- 제품이미지2
  PRODUCT_NAME VARCHAR2(200),                 -- 제품명_한글
  PRODUCT_NAME_ENG VARCHAR2(200),             -- 제품명_영문
  PRODUCT_DESCRIPTION VARCHAR2(200),          -- 제품간단설명
  PRODUCT_UNIT_PRICE NUMBER,		    	  -- 제품단가
  PRODUCT_COUNT NUMBER,						  -- 제품재고수량
  PRODUCT_CATEGORY_CD VARCHAR2(20),           -- 제품카테고리
  PRODUCT_REG_DATE VARCHAR2(20),              -- 제품등록일
  CONSTRAINT TB_PRODUCT_PK PRIMARY KEY(PRODUCT_CODE)
);

--판매내역정보
DROP TABLE TB_SELL CASCADE CONSTRAINT;
CREATE TABLE TB_SELL(
  SELL_CODE VARCHAR2(20),          -- 판매내역코드
  PRODUCT_CODE VARCHAR2(20),       -- 제품코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  SELL_PRICE NUMBER,      		   -- 판매총가격
  SELL_COUNT NUMBER,     		   -- 판매총수량
  SELL_YN VARCHAR2(1) DEFAULT 'N', -- 판매여부
  SELL_DATE VARCHAR2(30),          -- 판매일
  CONSTRAINT TB_SELL_PK PRIMARY KEY(SELL_CODE),
  CONSTRAINT TB_SELL_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_SELL_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--장바구니정보
DROP TABLE TB_CART CASCADE CONSTRAINT;
CREATE TABLE TB_CART(
  CART_CODE VARCHAR2(20),          -- 장바구니코드
  PRODUCT_CODE VARCHAR2(20),       -- 제품코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  CART_PRICE NUMBER,   		       -- 해당제품총가격
  CART_COUNT NUMBER,   		       -- 해당제품총수량
  CART_DATE VARCHAR2(30),          -- 장바구니 저장일
  CONSTRAINT TB_CART_PK PRIMARY KEY(CART_CODE),
  CONSTRAINT TB_CART_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_CART_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--댓글정보
DROP TABLE TB_REPLY CASCADE CONSTRAINT;
CREATE TABLE TB_REPLY(
  PRODUCT_CODE VARCHAR2(30),       -- 투표코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  USER_REPLY_NO NUMBER(3),         -- 댓글일련번호
  USER_REPLY VARCHAR2(1000),       -- 댓글내용
  REPLY_DATE VARCHAR2(30),         -- 댓글날짜
  CONSTRAINT TB_REPLY_PK PRIMARY KEY(PRODUCT_CODE, USER_CODE, USER_REPLY_NO),
  CONSTRAINT TB_REPLY_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_REPLY_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

--별점정보
DROP TABLE TB_MARK CASCADE CONSTRAINT;
CREATE TABLE TB_MARK(
  PRODUCT_CODE VARCHAR2(30),       -- 투표코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  MARK_RATING NUMBER,        	   -- 별점(5점만점)
  CONSTRAINT TB_MARK_PK PRIMARY KEY(PRODUCT_CODE, USER_CODE),
  CONSTRAINT TB_MARK_FK_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES TB_PRODUCT(PRODUCT_CODE),
  CONSTRAINT TB_MARK_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);

commit;

-- 공지사항 정보
-- 제약조건이 있는 테이블일 경우 DROP시 CASECADE CONSTRAINTS 옵션을 사용
DROP TABLE TB_NOTICE CASCADE CONSTRAINT;
CREATE TABLE TB_NOTICE(
  NTC_NO VARCHAR2(20),   	      	  -- 글번호
  NTC_TITLE VARCHAR2(50) NOT NULL,    -- 제목
  NTC_CONTENT VARCHAR2(4000), 	 	  -- 내용
  NTC_REG_ID VARCHAR2(20),    	 	  -- 등록자(수정자와 동일)
  NTC_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  NTC_MOD_DATE VARCHAR2(20),   		  -- 수정일자
  NTC_HIT NUMBER DEFAULT 0,    		  -- 조회수
  CONSTRAINT TB_NOTICE_PK PRIMARY KEY(NTC_NO)
);

-- 이벤트 정보
DROP TABLE TB_EVENT CASCADE CONSTRAINT;
CREATE TABLE TB_EVENT(
  EV_NO VARCHAR2(20),           	  -- 글번호
  EV_TITLE VARCHAR2(50) NOT NULL, 	  -- 제목
  EV_CONTENT VARCHAR2(4000),   	  	  -- 내용
  EV_REG_ID VARCHAR2(20),      	  	  -- 등록자
  EV_MOD_ID VARCHAR2(20),       	  -- 수정자
  EV_REG_DATE VARCHAR2(20),     	  -- 등록일자
  EV_MOD_DATE VARCHAR2(20),     	  -- 수정일자
  EV_HIT NUMBER DEFAULT 0,     	  	  -- 조회수
  CONSTRAINT TB_EVENT_PK PRIMARY KEY(EV_NO)
);

-- 커뮤니티 정보
DROP TABLE TB_COMMUNITY CASCADE CONSTRAINT;
CREATE TABLE TB_COMMUNITY(
  COMU_NO VARCHAR2(20),            	  -- 글번호
  COMU_TITLE VARCHAR2(50) NOT NULL,   -- 제목
  COMU_CONTENT VARCHAR2(4000),    	  -- 내용
  COMU_REG_ID VARCHAR2(20),      	  -- 등록자
  COMU_MOD_ID VARCHAR2(20),       	  -- 수정자
  COMU_REG_DATE VARCHAR2(20),     	  -- 등록일자
  COMU_MOD_DATE VARCHAR2(20),     	  -- 수정일자
  COMU_HIT NUMBER DEFAULT 0,      	  -- 조회수
  CONSTRAINT TB_COMMUNITY_PK PRIMARY KEY(COMU_NO)
);

-- 1:1문의 정보
DROP TABLE TB_INQUIRY CASCADE CONSTRAINT;
CREATE TABLE TB_INQUIRY(
  INQ_NO VARCHAR2(20),            	  -- 글번호
  INQ_TITLE VARCHAR2(50) NOT NULL,    -- 제목
  INQ_CONTENT VARCHAR2(4000),  		  -- 내용
  INQ_EMAIL VARCHAR2(50),             -- 이메일
  INQ_PHONE VARCHAR2(30),         	  -- 전화번호
  INQ_REG_ID VARCHAR2(20),   	      -- 등록자
  INQ_MOD_ID VARCHAR2(20),   	      -- 수정자
  INQ_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  INQ_MOD_DATE VARCHAR2(20),  	   	  -- 수정일자
  CONSTRAINT TB_INQUIRY_PK PRIMARY KEY(INQ_NO)
);

-- 갤러리 정보
DROP TABLE TB_GALERY CASCADE CONSTRAINT;
CREATE TABLE TB_GALERY(
	GAL_NO VARCHAR2(20),              -- 글번호
	GAL_UUID VARCHAR2(100),           -- 고유 식별자
	GAL_UPLOADPATH VARCHAR2(200),     -- 업로드 경로
	GAL_FILENAME VARCHAR2(100),       -- 파일 이름
	GAL_FILETYPE CHAR(1),             -- 파일 타입
	GAL_TITLE VARCHAR2(20),           -- 제목
	GAL_REG_ID VARCHAR2(20),          -- 등록자
	GAL_MOD_ID VARCHAR2(20),          -- 수정자
	GAL_REG_DATE VARCHAR2(20),        -- 등록일자
	GAL_MOD_DATE VARCHAR2(20),        -- 수벙일자
	GAL_HIT NUMBER,                   -- 조회수
	CONSTRAINT TB_GALERY_PK PRIMARY KEY(GAL_NO)
);

-- QNA 정보
DROP TABLE TB_QNA CASCADE CONSTRAINT;
CREATE TABLE TB_QNA(
	QNA_NO VARCHAR2(20),              -- 글번호
	QNA_TITLE VARCHAR2(20),           -- 제목
	QNA_CONTENT VARCHAR2(4000),       -- 내용
	QNA_REG_ID VARCHAR2(20),          -- 등록자
	QNA_MOD_ID VARCHAR2(20),          -- 수정자
	QNA_REG_DATE VARCHAR2(20),        -- 등록일자
	QNA_MOD_DATE VARCHAR2(20),        -- 수정일자
	CONSTRAINT TB_QNA_PK PRIMARY KEY(QNA_NO)
);

-- QNA 댓글 정보
DROP TABLE TB_QNA_REPLY CASCADE CONSTRAINT;
CREATE TABLE TB_QNA_REPLY(
	QNA_RNO VARCHAR2(20),             -- 글번호
	QNA_UUID VARCHAR2(100),           -- 고유 식별자
	QNA_NO VARCHAR2(20),              -- 글번호
	QNA_UPLOADPATH VARCHAR2(200),     -- 업로드 경로
	QNA_FILENAME VARCHAR2(100),       -- 파일 이름
	QNA_FILETYPE CHAR(1),             -- 파일 타입
	QNA_REPLY VARCHAR2(1000),         -- 댓글 내용
	QNA_REPLYER VARCHAR2(50),         -- 댓글 작성자
	QNA_REPLY_REG_DATE VARCHAR2(20),  -- 등록일자
	QNA_REPLY_MOD_DATE VARCHAR2(20),  -- 수정일자
	CONSTRAINT TB_QNA_REPLY_PK PRIMARY KEY(QNA_RNO),
	CONSTRAINT TB_QNA_REPLY_FK_QNA_NO FOREIGN KEY (QNA_NO) REFERENCES TB_QNA(QNA_NO)
);
commit;

--댓글정보

DROP SEQUENCE COMMENT_SEQ;
CREATE SEQUENCE COMMENT_SEQ;

DROP TABLE TB_COMMENT CASCADE CONSTRAINT;
CREATE TABLE TB_COMMENT(
  QNA_NO VARCHAR2(30),       -- 글코드
  USER_CODE VARCHAR2(20),          -- 유저코드
  USER_COMMENT_NO NUMBER(3),         -- 댓글일련번호
  USER_COMMENT VARCHAR2(1000),       -- 댓글내용
  COMMENT_DATE VARCHAR2(30),         -- 댓글날짜
  CONSTRAINT TB_COMMENT_PK PRIMARY KEY(QNA_NO, USER_CODE, USER_COMMENT_NO),
  CONSTRAINT TB_COMMENT_FK_QNA FOREIGN KEY(QNA_NO) REFERENCES TB_QNA(QNA_NO),
  CONSTRAINT TB_COMMENT_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);
commit;