
-- 일반 유저 테이블 생성
DROP TABLE ACCOUNTS CASCADE CONSTRAINT;
CREATE TABLE ACCOUNTS 
(
  IDX NUMBER NOT NULL
, USERID VARCHAR2(20 BYTE) NOT NULL 
, USERPASSWORD VARCHAR2(50 BYTE) NOT NULL 
, USERMAIL VARCHAR2(50 BYTE) NOT NULL 
, USERPHONE VARCHAR2(20 BYTE) NOT NULL 
, USERPROFILE VARCHAR2(100 BYTE) NOT NULL 
, USERNAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT ACCOUNTS_PK PRIMARY KEY 
  (
    IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ACCOUNTS_PK ON ACCOUNTS (IDX ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

commit;

-- 사용자 데이터 삽입
INSERT INTO ACCOUNTS(IDX, USERID, USERPASSWORD, USERMAIL, USERPHONE, USERPROFILE, USERNAME) 
VALUES ('0001', 'admin', 'admin', 'admin@admin.com', '010-1234-5678', '관리자', 'admin');

commit;

-- 네이버 유저 테이블 생성
DROP TABLE ACCOUNTS_NAVER CASCADE CONSTRAINT;
CREATE TABLE ACCOUNTS_NAVER
(
  IDX NUMBER NOT NULL 
, USERID VARCHAR2(20 BYTE) 
, USERNAME VARCHAR2(20 BYTE) 
, USERPASSWORD VARCHAR2(20 BYTE) 
, USERMAIL VARCHAR2(30 BYTE) 
, USERPHONE VARCHAR2(20 BYTE) 
, USERPROFILE VARCHAR2(100 BYTE) 
, USERFULLADDRESS VARCHAR2(100 BYTE) 
, USERSUBADDRESS VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

commit;
